### ISSUE TITLE
try out metacpan-api-test

### ISSUE THREAD

**Issue by melezhik** [CPAN-API/metacpan-api-test#1]
Hi @ranguard , @oalders !

This is is first try of metacpan-api functional tests.

As I am not deeply evolved into the metacpan API development, I chose a pretty straightforward approach in most of the tests:
- check if requests succeed ( is provided by swat out of the box )
- check is returned json hash has some keys ( mostly for the first level of nesting )

If it sounds ok, I can proceed the same way for other tests. But if you have some specific requirements for different API calls, lets discuss here.

Thanks

Alexey

**Comment by melezhik** [comment]
Hi @ranguard , @oalders ! If swat usage for metacpan still actual?  If so , please let me know so we could resume our collaboration )

**Comment by ranguard** [comment]
hi @melezhik - we are running the web branch of this - I'm not sure what we'd need specifically on the API side - users have been very responsive when there has been an issue :)

**Comment by oalders** [comment]
Hi @melezhik,

Do you have code for these new tests that I can look at or is this still in the discussion phase?

**Comment by melezhik** [comment]
Hi @oalders ! To be honest I have not actively developed new swat tests for a while. But I do like to proceed. I know many things have changed to metacpan recently , v~2~1 , etc. 

Meanwhile sparrow/swat/outthentic have grown quite a lot since I did last commit here, so I'd be happy to apply this toolchain for metacpan automation/testing things. 

My question in _general_ do you need any help of automation/or/and/testing for metacpan? so we could discuss. IRC or here :))

**Comment by melezhik** [comment]
But if in general you need some new examples of swat tests ( not for metacpan ), I could present some ...

**Comment by oalders** [comment]
@melezhik I think the most pressing need we have for tests is a test which checks the content of 02packages and then ensures that all packages listed in that file also have `status => 'latest'` in the API.

Is this something you could set up?  The only caveat is that files uploaded in the last 30m or so could be in 02packages, but won't necessarily be set as `latest`, so we'd have to allow for failures there.

**Comment by melezhik** [comment]
Hi Olaf ,I guess it's doable . Let't start new issue , as this one seems to be obsolete .

**Comment by melezhik** [comment]
Hi @oalders  , @ranguard ! I have dropped a first version ( quite raw but could be good as starting point ) -  of  [metacpan-api-packages-status](https://github.com/melezhik/metacpan-api-packages-status) , an example report could be found here - https://travis-ci.org/melezhik/metacpan-api-packages-status  ,this is sparrow plugin , so it needs a Sparrow client to get run. But let bring our discussion into a new issue? Don't you mind?

**Comment by oalders** [comment]
@melezhik sure, have you opened a new issue for the discussion?  It looks like a good starting point.  As far as the module endpoint goes, you can also limit the fields returned, so something like `https://fastapi.metacpan.org/v1/module/HTML::Restrict?fields=status,date` might be good.  We could ignore the status of modules which have dates within the last 30 or 60m.

**Comment by melezhik** [comment]
@oalders sure, just created one #2
